AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Rakefile'
Rails:
  Enabled: true
Layout/LineLength:
  Max: 100
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Metrics/BlockLength:
  ExcludedMethods: ['describe']
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20